from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings
from langchain.docstore.document import Document


import os
from create_pdf_list import ele1, ele2, ele3, ele4, ele5, ele6, ele7, ele8, ele9, ele10, ele11, ele12, ele13, ele14, ele15, ele16, ele17, ele18, ele19, ele20, ele21, ele22, ele23, ele24, ele25, ele26, ele27, ele28, ele29, ele30, ele31, ele32, ele33, ele34, ele35, ele36, ele37, ele38, ele39, ele40, ele41, ele42, ele43, ele44, ele45, ele46, ele47, ele48, ele49, ele50, ele51, ele52, ele53, ele54, ele55, ele56, ele57, ele58, ele59, ele60, ele61, ele62, ele63, ele64, ele65, ele66, ele67, ele68, ele69, ele70, ele71, ele72, ele73, ele74, ele75, ele76, ele77, ele78, ele79, ele80, ele81, ele82, ele83, ele84
doc1 =  Document(page_content=str(ele1),  metadata={"source": "local"})
doc2 =  Document(page_content=str(ele2),  metadata={"source": "local"})
doc3 =  Document(page_content=str(ele3),  metadata={"source": "local"})
doc4 =  Document(page_content=str(ele4),  metadata={"source": "local"})
doc5 =  Document(page_content=str(ele5),  metadata={"source": "local"})
doc6 =  Document(page_content=str(ele6),  metadata={"source": "local"})
doc7 =  Document(page_content=str(ele7),  metadata={"source": "local"})
doc8 =  Document(page_content=str(ele8),  metadata={"source": "local"})
doc9 =  Document(page_content=str(ele9),  metadata={"source": "local"})
doc10 =  Document(page_content=str(ele10),  metadata={"source": "local"})
doc11 =  Document(page_content=str(ele11),  metadata={"source": "local"})
doc12 =  Document(page_content=str(ele12),  metadata={"source": "local"})
doc13 =  Document(page_content=str(ele13),  metadata={"source": "local"})
doc14 =  Document(page_content=str(ele14),  metadata={"source": "local"})
doc15 =  Document(page_content=str(ele15),  metadata={"source": "local"})
doc16 =  Document(page_content=str(ele16),  metadata={"source": "local"})
doc17 =  Document(page_content=str(ele17),  metadata={"source": "local"})
doc18 =  Document(page_content=str(ele18),  metadata={"source": "local"})
doc19 =  Document(page_content=str(ele19),  metadata={"source": "local"})
doc20 =  Document(page_content=str(ele20),  metadata={"source": "local"})
doc21 =  Document(page_content=str(ele21),  metadata={"source": "local"})
doc22 =  Document(page_content=str(ele22),  metadata={"source": "local"})
doc23 =  Document(page_content=str(ele23),  metadata={"source": "local"})
doc24 =  Document(page_content=str(ele24),  metadata={"source": "local"})
doc25 =  Document(page_content=str(ele25),  metadata={"source": "local"})
doc26 =  Document(page_content=str(ele26),  metadata={"source": "local"})
doc27 =  Document(page_content=str(ele27),  metadata={"source": "local"})
doc28 =  Document(page_content=str(ele28),  metadata={"source": "local"})
doc29 =  Document(page_content=str(ele29),  metadata={"source": "local"})
doc30 =  Document(page_content=str(ele30),  metadata={"source": "local"})
doc31 =  Document(page_content=str(ele31),  metadata={"source": "local"})
doc32 =  Document(page_content=str(ele32),  metadata={"source": "local"})
doc33 =  Document(page_content=str(ele33),  metadata={"source": "local"})
doc34 =  Document(page_content=str(ele34),  metadata={"source": "local"})
doc35 =  Document(page_content=str(ele35),  metadata={"source": "local"})
doc36 =  Document(page_content=str(ele36),  metadata={"source": "local"})
doc37 =  Document(page_content=str(ele37),  metadata={"source": "local"})
doc38 =  Document(page_content=str(ele38),  metadata={"source": "local"})
doc39 =  Document(page_content=str(ele39),  metadata={"source": "local"})
doc40 =  Document(page_content=str(ele40),  metadata={"source": "local"})
doc41 =  Document(page_content=str(ele41),  metadata={"source": "local"})
doc42 =  Document(page_content=str(ele42),  metadata={"source": "local"})
doc43 =  Document(page_content=str(ele43),  metadata={"source": "local"})
doc44 =  Document(page_content=str(ele44),  metadata={"source": "local"})
doc45 =  Document(page_content=str(ele45),  metadata={"source": "local"})
doc46 =  Document(page_content=str(ele46),  metadata={"source": "local"})
doc47 =  Document(page_content=str(ele47),  metadata={"source": "local"})
doc48 =  Document(page_content=str(ele48),  metadata={"source": "local"})
doc49 =  Document(page_content=str(ele49),  metadata={"source": "local"})
doc50 =  Document(page_content=str(ele50),  metadata={"source": "local"})
doc51 =  Document(page_content=str(ele51),  metadata={"source": "local"})
doc52 =  Document(page_content=str(ele52),  metadata={"source": "local"})
doc53 =  Document(page_content=str(ele53),  metadata={"source": "local"})
doc54 =  Document(page_content=str(ele54),  metadata={"source": "local"})
doc55 =  Document(page_content=str(ele55),  metadata={"source": "local"})
doc56 =  Document(page_content=str(ele56),  metadata={"source": "local"})
doc57 =  Document(page_content=str(ele57),  metadata={"source": "local"})
doc58 =  Document(page_content=str(ele58),  metadata={"source": "local"})
doc59 =  Document(page_content=str(ele59),  metadata={"source": "local"})
doc60 =  Document(page_content=str(ele60),  metadata={"source": "local"})
doc61 =  Document(page_content=str(ele61),  metadata={"source": "local"})
doc62 =  Document(page_content=str(ele62),  metadata={"source": "local"})
doc63 =  Document(page_content=str(ele63),  metadata={"source": "local"})
doc64 =  Document(page_content=str(ele64),  metadata={"source": "local"})
doc65 =  Document(page_content=str(ele65),  metadata={"source": "local"})
doc66 =  Document(page_content=str(ele66),  metadata={"source": "local"})
doc67 =  Document(page_content=str(ele67),  metadata={"source": "local"})
doc68 =  Document(page_content=str(ele68),  metadata={"source": "local"})
doc69 =  Document(page_content=str(ele69),  metadata={"source": "local"})
doc70 =  Document(page_content=str(ele70),  metadata={"source": "local"})
doc71 =  Document(page_content=str(ele71),  metadata={"source": "local"})
doc72 =  Document(page_content=str(ele72),  metadata={"source": "local"})
doc73 =  Document(page_content=str(ele73),  metadata={"source": "local"})
doc74 =  Document(page_content=str(ele74),  metadata={"source": "local"})
doc75 =  Document(page_content=str(ele75),  metadata={"source": "local"})
doc76 =  Document(page_content=str(ele76),  metadata={"source": "local"})
doc77 =  Document(page_content=str(ele77),  metadata={"source": "local"})
doc78 =  Document(page_content=str(ele78),  metadata={"source": "local"})
doc79 =  Document(page_content=str(ele79),  metadata={"source": "local"})
doc80 =  Document(page_content=str(ele80),  metadata={"source": "local"})
doc81 =  Document(page_content=str(ele81),  metadata={"source": "local"})
doc82 =  Document(page_content=str(ele82),  metadata={"source": "local"})
doc83 =  Document(page_content=str(ele83),  metadata={"source": "local"})
doc84 =  Document(page_content=str(ele84),  metadata={"source": "local"})


folder_name = "./db"

def create_db(folder_name):
        texts = [doc1, doc2, doc3, doc4, doc5, doc6, doc7, doc8, doc9, doc10, doc11, doc12, doc13, doc14, doc15, doc16, doc17, doc18, doc19, doc20, doc21, doc22, doc23, doc24, doc25, doc26, doc27, doc28, doc29, doc30, doc31, doc32, doc33, doc34, doc35, doc36, doc37, doc38, doc39, doc40, doc41, doc42, doc43, doc44, doc45, doc46, doc47, doc48, doc49, doc50, doc51, doc52, doc53, doc54, doc55, doc56, doc57, doc58, doc59, doc60, doc61, doc62, doc63, doc64, doc65, doc66, doc67, doc68, doc69, doc70, doc71, doc72, doc73, doc74, doc75, doc76, doc77, doc78, doc79, doc80, doc81, doc82, doc83, doc84]
        embedding = OpenAIEmbeddings()
        vectordb = Chroma.from_documents(documents=texts, embedding=embedding, persist_directory=folder_name)
        vectordb.persist()
        vectordb = None
        print("db created Successfully")

# def get_context(query):
#     embedding = OpenAIEmbeddings()
#     vectordb = Chroma(persist_directory=folder_name, embedding_function=embedding)
#     docs = vectordb.similarity_search(query,k=2,search_type="similarity")

# query = "placenta previa"
# docs = get_context("")
# print(docs)
